import { join } from "node:path";
import type { LogicalConfig } from "@codemcp/ade-core";
import type { HarnessWriter } from "../types.js";
import {
  readJsonOrEmpty,
  writeMcpServers,
  alwaysAllowEntry,
  writeRulesFile,
  writeGitHooks,
  writeJson
} from "../util.js";
import { allowsCapability, hasPermissionPolicy } from "../permission-policy.js";

export const rooCodeWriter: HarnessWriter = {
  id: "roo-code",
  label: "Roo Code",
  description: "AI coding agent — .roo/mcp.json + .roomodes + .roorules",
  async install(config: LogicalConfig, projectRoot: string) {
    await writeMcpServers(config.mcp_servers, {
      path: join(projectRoot, ".roo", "mcp.json"),
      transform: alwaysAllowEntry
    });

    await writeRooModes(config, projectRoot);
    await writeRulesFile(config.instructions, join(projectRoot, ".roorules"));
    await writeGitHooks(config.git_hooks, projectRoot);
  }
};

async function writeRooModes(
  config: LogicalConfig,
  projectRoot: string
): Promise<void> {
  if (!hasPermissionPolicy(config)) {
    return;
  }

  const roomodesPath = join(projectRoot, ".roomodes");
  const existing = await readJsonOrEmpty(roomodesPath);
  const existingCustomModes = asRecord(existing.customModes);

  await writeJson(roomodesPath, {
    ...existing,
    customModes: {
      ...existingCustomModes,
      ade: {
        slug: "ade",
        name: "ADE",
        roleDefinition:
          "ADE — Agentic Development Environment mode generated by ADE.",
        groups: getRooModeGroups(config),
        source: "project"
      }
    }
  });
}

function asRecord(value: unknown): Record<string, unknown> {
  return value !== null &&
    typeof value === "object" &&
    !Array.isArray(value)
    ? (value as Record<string, unknown>)
    : {};
}

function getRooModeGroups(config: LogicalConfig): string[] {
  return [
    ...(allowsCapability(config, "read") ? ["read"] : []),
    ...(allowsCapability(config, "edit_write") ? ["edit"] : []),
    ...(allowsCapability(config, "bash_unsafe") ? ["command"] : []),
    ...(config.mcp_servers.length > 0 ? ["mcp"] : [])
  ];
}
