import { join } from "node:path";
import type { AutonomyProfile, LogicalConfig } from "@codemcp/ade-core";
import type { HarnessWriter } from "../types.js";
import {
  readJsonOrEmpty,
  writeMcpServers,
  alwaysAllowEntry,
  writeRulesFile,
  writeGitHooks,
  writeJson,
  pathExists
} from "../util.js";
import {
  getAutonomyProfile,
  hasPermissionPolicy
} from "../permission-policy.js";

export const rooCodeWriter: HarnessWriter = {
  id: "roo-code",
  label: "Roo Code",
  description: "AI coding agent — .roo/mcp.json + .roomodes + .roorules",
  verified: false,
  async detect(projectRoot: string) {
    return (
      (await pathExists(join(projectRoot, ".roo"))) ||
      (await pathExists(join(projectRoot, ".roomodes"))) ||
      (await pathExists(join(projectRoot, ".roorules")))
    );
  },
  async install(config: LogicalConfig, projectRoot: string) {
    await writeMcpServers(config.mcp_servers, {
      path: join(projectRoot, ".roo", "mcp.json"),
      transform: alwaysAllowEntry
    });

    await writeRooModes(config, projectRoot);
    await writeRulesFile(config.instructions, join(projectRoot, ".roorules"));
    await writeGitHooks(config.git_hooks, projectRoot);
  }
};

async function writeRooModes(
  config: LogicalConfig,
  projectRoot: string
): Promise<void> {
  if (!hasPermissionPolicy(config)) {
    return;
  }

  const roomodesPath = join(projectRoot, ".roomodes");
  const existing = await readJsonOrEmpty(roomodesPath);
  const existingCustomModes = asRecord(existing.customModes);

  await writeJson(roomodesPath, {
    ...existing,
    customModes: {
      ...existingCustomModes,
      ade: {
        slug: "ade",
        name: "ADE",
        roleDefinition:
          "ADE — Agentic Development Environment mode generated by ADE.",
        groups: getRooModeGroups(
          getAutonomyProfile(config),
          config.mcp_servers.length > 0
        ),
        source: "project"
      }
    }
  });
}

function asRecord(value: unknown): Record<string, unknown> {
  return value !== null && typeof value === "object" && !Array.isArray(value)
    ? (value as Record<string, unknown>)
    : {};
}

function getRooModeGroups(
  profile: AutonomyProfile | undefined,
  hasMcpServers: boolean
): string[] {
  const mcpGroup = hasMcpServers ? ["mcp"] : [];

  switch (profile) {
    case "rigid":
      return ["read", ...mcpGroup];
    case "sensible-defaults":
      return ["read", "edit", ...mcpGroup];
    case "max-autonomy":
      return ["read", "edit", "command", ...mcpGroup];
    default:
      return ["read", "edit", "command", ...mcpGroup];
  }
}
